### ISSUE TITLE
Seus arquivos são .cpp mas seus códigos são C

### ISSUE THREAD

**Issue by tkovs** [vieirafrancisco/Francisco-Vieira#7]
https://github.com/vieirafrancisco/Francisco-Vieira/blob/c3f1eaa719ad4c7740bcbb4e3163b17c784c211c/Atividade-Condicionais-e-Estruturas-de-Repeti%C3%A7%C3%A3o/matriculas_duplas.cpp#L1

**Comment by vieirafrancisco** [comment]
No inicio era porque eu só usava os comandos de C, mas depois eu comecei a misturar um e outro, ai resolvi só usar somente .cpp rs. Como é para resolução de questões creio que não tem problema. Obrigado ai! e desculpa a demora :smiley:

**Comment by tkovs** [comment]
Pode fechar rsrs
